version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"  # Changed from weekly to daily for faster security updates
      time: "09:00"
      timezone: "America/Edmonton"
    open-pull-requests-limit: 10  # Increased from 5 to allow more updates
    target-branch: "develop"
    reviewers:
      - "PixelRidgeSoftworks"
    assignees:
      - "PixelRidgeSoftworks"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
      - "auto-update"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Removed ignore block to allow major version updates with proper grouping
    groups:
      # Security updates - highest priority
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      
      # Major version updates - group for careful review
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
      
      # Framework updates - group core dependencies
      framework-updates:
        patterns:
          - "sinatra*"
          - "rack*"
          - "sequel*"
          - "puma*"
          - "thin*"
        update-types:
          - "minor"
          - "patch"
      
      # Database and ORM updates
      database-updates:
        patterns:
          - "sqlite3*"
          - "mysql2*"
          - "pg*"
        update-types:
          - "minor"
          - "patch"
      
      # Payment and security API dependencies
      payment-security-updates:
        patterns:
          - "stripe*"
          - "paypal*"
          - "jwt*"
          - "bcrypt*"
          - "faraday*"
          - "httparty*"
        update-types:
          - "minor"
          - "patch"
      
      # Development and testing tools
      dev-tools:
        dependency-type: "development"
        patterns:
          - "rubocop*"
          - "minitest*"
          - "simplecov*"
          - "rack-test*"
          - "factory_bot*"
      
      # Utility and helper gems - safe to update
      utilities:
        patterns:
          - "dotenv*"
          - "concurrent-ruby*"
          - "mail*"
          - "tilt*"
          - "erubi*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Edmonton"
    open-pull-requests-limit: 3
    target-branch: "develop"
    reviewers:
      - "PixelRidgeSoftworks"
    assignees:
      - "PixelRidgeSoftworks"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    groups:
      github-actions:
        patterns:
          - "*"
