version: 2
updates:
  # Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"  # Changed from weekly to daily for faster security updates
      time: "09:00"
      timezone: "America/Edmonton"
    open-pull-requests-limit: 10  # Increased from 5 to allow more updates
    target-branch: "develop"
    reviewers:
      - "PixelRidgeSoftworks"
    assignees:
      - "PixelRidgeSoftworks"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
      - "auto-update"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Removed ignore block to allow major version updates with proper grouping
    groups:
      # High priority security updates (processed immediately)
      critical-security:
        patterns:
          - "*"
        update-types:
          - "security"
        priority: 10
      
      # Major version updates (grouped together for easier review)
      major-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
        priority: 5
      
      # Minor and patch updates (grouped by category)
      framework-updates:
        patterns:
          - "sinatra*"
          - "rack*"
          - "sequel*"
          - "puma*"
          - "thin*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
        priority: 8
      
      # Database and ORM updates
      database-updates:
        patterns:
          - "sqlite3*"
          - "mysql2*"
          - "pg*"
          - "sequel*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
        priority: 7
      
      # Payment and API dependencies
      payment-api-updates:
        patterns:
          - "stripe*"
          - "paypal*"
          - "jwt*"
          - "bcrypt*"
          - "faraday*"
          - "httparty*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
        priority: 8
      
      # Development and testing dependencies
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "rubocop*"
          - "minitest*"
          - "simplecov*"
          - "rack-test*"
          - "factory_bot*"
        priority: 3
      
      # Utility and helper gems
      utility-updates:
        patterns:
          - "dotenv*"
          - "concurrent-ruby*"
          - "mail*"
          - "tilt*"
          - "erubi*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
        priority: 6
      
      # Everything else (catch-all for ungrouped dependencies)
      other-dependencies:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
        priority: 4

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "America/Edmonton"
    open-pull-requests-limit: 3
    target-branch: "develop"
    reviewers:
      - "PixelRidgeSoftworks"
    assignees:
      - "PixelRidgeSoftworks"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    groups:
      github-actions:
        patterns:
          - "*"
