name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
          bundler-cache: true
      
      - name: Run tests
        run: |
          bundle exec ruby run_tests.rb
        continue-on-error: false
      
      - name: Check if auto-merge is allowed
        id: auto-merge-check
        run: |
          # Define conditions for auto-merge
          UPDATE_TYPE="${{ steps.metadata.outputs.update-type }}"
          DEPENDENCY_TYPE="${{ steps.metadata.outputs.dependency-type }}"
          DEPENDENCY_NAME="${{ steps.metadata.outputs.dependency-names }}"
          
          echo "Update type: $UPDATE_TYPE"
          echo "Dependency type: $DEPENDENCY_TYPE"
          echo "Dependency name: $DEPENDENCY_NAME"
          
          # Auto-merge conditions
          AUTO_MERGE="false"
          
          # Always auto-merge security updates
          if [[ "$UPDATE_TYPE" == "version-update:semver-patch" && "${{ steps.metadata.outputs.alert-state }}" == "FIXED" ]]; then
            echo "Security patch detected - auto-merge enabled"
            AUTO_MERGE="true"
          fi
          
          # Auto-merge patch updates for safe dependencies
          if [[ "$UPDATE_TYPE" == "version-update:semver-patch" ]]; then
            case "$DEPENDENCY_NAME" in
              *rubocop*|*minitest*|*simplecov*|*rack-test*)
                echo "Safe development dependency patch - auto-merge enabled"
                AUTO_MERGE="true"
                ;;
              *dotenv*|*concurrent-ruby*|*mail*|*tilt*|*erubi*)
                echo "Safe utility dependency patch - auto-merge enabled"
                AUTO_MERGE="true"
                ;;
              *jwt*|*bcrypt*)
                echo "Security-related patch - auto-merge enabled"
                AUTO_MERGE="true"
                ;;
            esac
          fi
          
          # Auto-merge minor updates for development dependencies only
          if [[ "$UPDATE_TYPE" == "version-update:semver-minor" && "$DEPENDENCY_TYPE" == "development" ]]; then
            echo "Development dependency minor update - auto-merge enabled"
            AUTO_MERGE="true"
          fi
          
          echo "auto-merge=$AUTO_MERGE" >> $GITHUB_OUTPUT
      
      - name: Auto-merge Dependabot PR
        if: steps.auto-merge-check.outputs.auto-merge == 'true'
        run: |
          echo "Auto-merging Dependabot PR #${{ github.event.pull_request.number }}"
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add auto-merge label
        if: steps.auto-merge-check.outputs.auto-merge == 'true'
        run: |
          gh pr edit "${{ github.event.pull_request.number }}" --add-label "auto-merged"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment on manual review needed
        if: steps.auto-merge-check.outputs.auto-merge == 'false'
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "🔍 **Manual Review Required**
          
          This Dependabot update requires manual review because:
          - Update type: \`${{ steps.metadata.outputs.update-type }}\`
          - Dependency type: \`${{ steps.metadata.outputs.dependency-type }}\`
          - Dependency: \`${{ steps.metadata.outputs.dependency-names }}\`
          
          Please review the changes and merge manually if appropriate.
          
          **Auto-merge criteria:**
          - ✅ Security patches (all dependencies)
          - ✅ Patch updates for safe utilities (dotenv, mail, etc.)
          - ✅ Development dependency minor updates
          - ✅ Security-related patches (jwt, bcrypt)
          - ❌ Major version updates (manual review required)
          - ❌ Framework updates (Sinatra, Rack, Sequel - manual review required)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add manual review label
        if: steps.auto-merge-check.outputs.auto-merge == 'false'
        run: |
          gh pr edit "${{ github.event.pull_request.number }}" --add-label "manual-review-required"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: auto-merge
    if: failure() && github.actor == 'dependabot[bot]'
    
    steps:
      - name: Comment on test failure
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "❌ **Auto-merge Failed**
          
          Tests failed for this Dependabot update. Please check the workflow logs and resolve any issues.
          
          [View workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add failure label
        run: |
          gh pr edit "${{ github.event.pull_request.number }}" --add-label "tests-failed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
